export const WORDS = [
  'MAISON',
  'VOITURE',
  'VELO',
  'MONTAGNE',
  'RIVIERE',
  'OCEAN',
  'PLAGE',
  'FORET',
  'ARBRE',
  'FLEUR',
  'JARDIN',
  'SOLEIL',
  'LUNE',
  'ETOILE',
  'NUAGE',
  'PLUIE',
  'VENT',
  'NEIGE',
  'ORAGE',
  'ARCENCIEL',
  'CHAT',
  'CHIEN',
  'LION',
  'TIGRE',
  'ELEPHANT',
  'GIRAFE',
  'SINGE',
  'CHEVAL',
  'LAPIN',
  'POISSON',
  'DAUPHIN',
  'BALEINE',
  'AIGLE',
  'PAPILLON',
  'ABEILLE',
  'POMME',
  'BANANE',
  'ORANGE',
  'MANGUE',
  'ANANAS',
  'FRAISE',
  'CERISE',
  'RAISIN',
  'PASTEQUE',
  'CITRON',
  'PAIN',
  'FROMAGE',
  'CHOCOLAT',
  'GATEAU',
  'PIZZA',
  'CUISINE',
  'RESTAURANT',
  'HOTEL',
  'ECOLE',
  'UNIVERSITE',
  'BIBLIOTHEQUE',
  'HOPITAL',
  'MARCHE',
  'AEROPORT',
  'GARE',
  'MUSEE',
  'CINEMA',
  'THEATRE',
  'PARC',
  'STADE',
  'PISCINE',
  'FOOTBALL',
  'BASKET',
  'TENNIS',
  'NATATION',
  'COURSE',
  'VELO',
  'MUSIQUE',
  'CHANT',
  'DANSE',
  'GUITARE',
  'PIANO',
  'VIOLON',
  'LIVRE',
  'HISTOIRE',
  'AVENTURE',
  'VOYAGE',
  'VACANCES',
  'AMITIE',
  'FAMILLE',
  'BONHEUR',
  'COURAGE',
  'PATIENCE',
  'SOURIRE',
  'ESPOIR',
  'LIBERTE',
  'JUSTICE',
  'PEINTURE',
  'SCULPTURE',
  'PHOTO',
  'CAMERA',
  'MONTRE',
  'LAMPE',
  'MIROIR',
  'VALISE',
  'PARAPLUIE',
  'BOUGIE',
  'COUSSIN'
];
export function pickRandomWord() {
  const index = Math.floor(Math.random() * WORDS.length);
  return WORDS[index];
}

// Renvoie le mot avec les lettres devinées visibles et les autres cachées : "R _ A _ T"
export function getDisplayWord(word, guessedLetters) {
  return word
    .split('')
    .map((letter) => (guessedLetters.includes(letter) ? letter : '_'))
    .join(' ');
}

export function isWordFound(word, guessedLetters) {
  return word.split('').every((letter) => guessedLetters.includes(letter));
}